### PR TITLE
change to use pointers

### PR DESCRIPTION
**Pull request by searchivarius**
1. Upgrade of linux-perf 
2. Passing all posting lists as pointers to constant objects
3. Using #ifdef to hide AVX2 code
4. -march=native in Makefile
5. making it c++17 to have an easy iteration over maps (this can be changed to be c++-11 compliant if necessary)

### CODE REVIEW

**Comment by lemire** [comment]
Let us merge!

**Comment by searchivarius** [comment]
Thank you @lemire please check if it works for you! I am quite curious, I couldn't check the AVX2 case in the end-to-end test. On my MAC machine I don't have Linux, on my AMD machine I don't have AVX2 and on AWS there's no linux-perf :-)

**Comment by searchivarius** [comment]
PS: so checked some pieces separately only

**Comment by searchivarius** [comment]
PPS: I also worry a bit about  -march=native

**Comment by lemire** [comment]
Yes. I removed "-march=native". It is both unnecessary and harmful to performance in this case.

Otherwise, it works.

**Pull request merged**
